
catalog:
  api:
    base-url: https://catalog-workshop-yequy5sv5a-uc.a.run.app
    products-uri: /catalog/products/byIds
    product-uri: /catalog/products/{id}
    discount-uri: /catalog/products/{product_id}/price-checkout?quantity={quantity}
    volumePromotion-uri: http://localhost:8081/catalog/products/volumePromotion

users:
  api:
    base-url: https://user-microservice-ey3npq3qvq-uc.a.run.app
    users-uri: /users/{id}